/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef litescreen_CONSTANTS_H
#define litescreen_CONSTANTS_H

#include "litescreen_types.h"

namespace thrift { namespace litescreen {

class litescreenConstants {
 public:
  litescreenConstants();

  int32_t FROM_LINUX;
  int32_t FROM_WINDOWS;
};

extern const litescreenConstants g_litescreen_constants;

}} // namespace

#endif
