/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "litescreen_constants.h"

namespace thrift { namespace litescreen {

const litescreenConstants g_litescreen_constants;

litescreenConstants::litescreenConstants() {
  FROM_LINUX = 0;

  FROM_WINDOWS = 1;

}

}} // namespace

